# Generated by Django 4.1.3 on 2023-04-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OLX_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=1, upload_to='photo_category/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
